# 这是一个基本的工作流程，可帮助您开始使用操作 
# name 为 Workflow 的名字
name: CI

# Controls when the workflow will run
# on 触发的Events，可以是一个Events数组
on:
  # 在推或拉请求事件上触发工作流，但仅针对 "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 允许您从“操作”选项卡手动运行此工作流 
  workflow_dispatch:

# 工作流运行由可以顺序或并行运行的一个或多个作业组成 
jobs:
  # 此工作流程包含一个名为 build 的作业
  build:
    # 环境：作业将运行的运行程序类型
    runs-on: ubuntu-latest

    # 步骤表示将作为工作一部分执行的一系列任务 
    steps:
      # 在$GITHUB_WORKSPACE下签出您的存储库，以便您的作业可以访问它
      - uses: actions/checkout@v3

      # 执行某个shell命令或脚本
      # 构建编译
      - name: build start
        run: |
          npm install
          npm run build 

      # 编译结束
      - name: build end
        run: echo build success.
