# originBuild.yml
# 一个 workflow：远程构建编译
name: CI

# 触发 workflow 的事件
# on 触发的Events，可以是一个Events数组
on:
  # 在推或拉请求事件上触发工作流，但仅针对 "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 允许您从“操作”选项卡手动运行此工作流 
  workflow_dispatch:

# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest

    # steps是每个Job的运行步骤，可以包含一个或多个步骤
    steps:
      # 使用action库  actions/checkout获取源码
      - uses: actions/checkout@v3

      # action命令，安装 Node 14
      - name: Use Node.js 14
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # action命令，install && build
      - name: npm install and build
        # 运行的命令或者 action
        run: echo build start.

      # 编译结束
      - name: build end
        run: echo build end.
